Strings to secret waypoints :D
odtheking/OdinClient pull request #37
Opened 2024-03-25 23:05 UTC by AzaelMew

![Snapchat-632930763](https://github.com/odtheking/OdinClient/assets/66936848/5028f1d7-88aa-472a-bd44-23f52c3342c5)
Cute cat so u cant say no ^^

2024-03-26 19:00 UTC, freebonsai commented on odinmain/src/main/kotlin/me/odinmain/commands/impl/DevCommand.kt
> +        val northPos = Vec2(xPos, zPos - 4)
Just remove this from the message, it's redundant as the scanning no longer uses rotation cores.

2024-03-26 19:01 UTC, freebonsai commented on odinmain/src/main/kotlin/me/odinmain/features/impl/dungeon/DungeonWaypoints.kt
> +            Renderer.drawStringInWorld(it.title.toString(), Vec3(it.x+0.5,it.y+0.5,it.z+0.5))
Replace ´it.title.toString()" with "it.title ?: ""   ´
This removes the need for the function to replace "null"

2024-03-26 19:02 UTC, freebonsai commented on odinmain/src/main/kotlin/me/odinmain/utils/render/Renderer.kt
> +    //Edited to make null value not crash the game, as if config doesn't have a title it will crash game otherwise.
Do my suggestion in DungeonWaypoints.kt and remove this change.

2024-03-26 19:03 UTC, freebonsai requested changes
Take care of my comments and I will merge.

2024-03-27 01:17 UTC, AzaelMew commented
Fixed what u told me to :D

2024-03-27 16:44 UTC, freebonsai commented on odinmain/src/main/kotlin/me/odinmain/features/impl/dungeon/DungeonWaypoints.kt
> +    class GuiSign : GuiScreen() {
Make this an object instead of a class, you can still achieve the same result, look at TermSim objects if you need.

2024-03-27 16:44 UTC, freebonsai commented on odinmain/src/main/kotlin/me/odinmain/features/impl/dungeon/DungeonWaypoints.kt
> +    private val color: Color by ColorSetting(
I see no need to expand these, it makes the code longer for no reason.

2024-03-27 16:45 UTC, freebonsai commented on odinmain/src/main/kotlin/me/odinmain/features/impl/dungeon/DungeonWaypoints.kt
> +                waypoints.add(
Do this in one line

2024-03-27 16:46 UTC, freebonsai commented on odinmain/src/main/kotlin/me/odinmain/features/impl/dungeon/DungeonWaypoints.kt
> +    fun DungeonWaypoint.toAABB(size: Double) = AxisAlignedBB(
The expansion is fine here as they all line up and are very similar

2024-03-27 16:47 UTC, freebonsai requested changes
Look over comments, looks good though.

2024-03-27 20:38 UTC, freebonsai approved these changes
Good.

2024-03-27 20:43 UTC, merged